### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by MarcoGro** [pollti/NewTabHere#2]
New Tab Here does not work,
new tabs are not opened next to the active tab but always at the bottom of all tabs (Firefox 64.0.2 64Bit)

**Comment by MarcoGro** [comment]
Once done, New Tab Here did not get along with New Tab Override, after New Tab Override's permissions were revoked and granted again, New Tab Here finally worked

**Comment by pollti** [comment]
Thanks, seems reasonable.
